### ISSUE TITLE
Review and/or update Workshop description

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/2021-07-19-cms-open-data-workshop#8]
The workshop description at `_includes/swc/intro.html` needs revision.

**Comment by mattbellis** [comment]
Putting this here.....

Suggested text for the workshop description. 

Since 2014, the CMS Collaboration has pioneered the release of LHC research quality data for public use by making a significant amount of these data accessible through the CERN Open Data portal. In 2020, the collaboration initiated a first-of-its-kind CMS Open Data Workshop where theorists, phenomenologists, and other interested researchers can learn more about how to interact with and analyze these vast datasets. This is the second version of that workshop and should benefit both new participants and attendees of the first iteration. The workshop aims to bridge the technical gap
that usually exists between the scientific creativity of an external analyst and the nuts-and-bolts details of a full analysis with CMS open data. All exercises will be hands-on and participants should be prepared to dive into the
data right away. A set of pre-exercises and assignments are provided and required for participants
so that they can make the most of the workshop. Time will also be spent brainstorming with attendees about how the
entire process of accessing and analyzing the data could be made more useful for the broader HEP community.

**Comment by caredg** [comment]
Sounds great Matt, thanks!
-e

**Comment by mattbellis** [comment]
Great! I'll get this uploaded and will close this issue out when I do!

**Comment by mattbellis** [comment]
Done. Made the edits to Indico and then edited the `_includes/swc/intro.html` through the web-browser on Github.
